require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MedicationReportsController do

  # This should return the minimal set of attributes required to create a valid
  # MedicationReport. As you add validations to MedicationReport, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all medication_reports as @medication_reports" do
      medication_report = MedicationReport.create! valid_attributes
      get :index
      assigns(:medication_reports).should eq([medication_report])
    end
  end

  describe "GET show" do
    it "assigns the requested medication_report as @medication_report" do
      medication_report = MedicationReport.create! valid_attributes
      get :show, :id => medication_report.id
      assigns(:medication_report).should eq(medication_report)
    end
  end

  describe "GET new" do
    it "assigns a new medication_report as @medication_report" do
      get :new
      assigns(:medication_report).should be_a_new(MedicationReport)
    end
  end

  describe "GET edit" do
    it "assigns the requested medication_report as @medication_report" do
      medication_report = MedicationReport.create! valid_attributes
      get :edit, :id => medication_report.id
      assigns(:medication_report).should eq(medication_report)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MedicationReport" do
        expect {
          post :create, :medication_report => valid_attributes
        }.to change(MedicationReport, :count).by(1)
      end

      it "assigns a newly created medication_report as @medication_report" do
        post :create, :medication_report => valid_attributes
        assigns(:medication_report).should be_a(MedicationReport)
        assigns(:medication_report).should be_persisted
      end

      it "redirects to the created medication_report" do
        post :create, :medication_report => valid_attributes
        response.should redirect_to(MedicationReport.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved medication_report as @medication_report" do
        # Trigger the behavior that occurs when invalid params are submitted
        MedicationReport.any_instance.stub(:save).and_return(false)
        post :create, :medication_report => {}
        assigns(:medication_report).should be_a_new(MedicationReport)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MedicationReport.any_instance.stub(:save).and_return(false)
        post :create, :medication_report => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested medication_report" do
        medication_report = MedicationReport.create! valid_attributes
        # Assuming there are no other medication_reports in the database, this
        # specifies that the MedicationReport created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MedicationReport.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => medication_report.id, :medication_report => {'these' => 'params'}
      end

      it "assigns the requested medication_report as @medication_report" do
        medication_report = MedicationReport.create! valid_attributes
        put :update, :id => medication_report.id, :medication_report => valid_attributes
        assigns(:medication_report).should eq(medication_report)
      end

      it "redirects to the medication_report" do
        medication_report = MedicationReport.create! valid_attributes
        put :update, :id => medication_report.id, :medication_report => valid_attributes
        response.should redirect_to(medication_report)
      end
    end

    describe "with invalid params" do
      it "assigns the medication_report as @medication_report" do
        medication_report = MedicationReport.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MedicationReport.any_instance.stub(:save).and_return(false)
        put :update, :id => medication_report.id, :medication_report => {}
        assigns(:medication_report).should eq(medication_report)
      end

      it "re-renders the 'edit' template" do
        medication_report = MedicationReport.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MedicationReport.any_instance.stub(:save).and_return(false)
        put :update, :id => medication_report.id, :medication_report => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested medication_report" do
      medication_report = MedicationReport.create! valid_attributes
      expect {
        delete :destroy, :id => medication_report.id
      }.to change(MedicationReport, :count).by(-1)
    end

    it "redirects to the medication_reports list" do
      medication_report = MedicationReport.create! valid_attributes
      delete :destroy, :id => medication_report.id
      response.should redirect_to(medication_reports_url)
    end
  end

end
