require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MigraineReportsController do

  # This should return the minimal set of attributes required to create a valid
  # MigraineReport. As you add validations to MigraineReport, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all migraine_reports as @migraine_reports" do
      migraine_report = MigraineReport.create! valid_attributes
      get :index
      assigns(:migraine_reports).should eq([migraine_report])
    end
  end

  describe "GET show" do
    it "assigns the requested migraine_report as @migraine_report" do
      migraine_report = MigraineReport.create! valid_attributes
      get :show, :id => migraine_report.id
      assigns(:migraine_report).should eq(migraine_report)
    end
  end

  describe "GET new" do
    it "assigns a new migraine_report as @migraine_report" do
      get :new
      assigns(:migraine_report).should be_a_new(MigraineReport)
    end
  end

  describe "GET edit" do
    it "assigns the requested migraine_report as @migraine_report" do
      migraine_report = MigraineReport.create! valid_attributes
      get :edit, :id => migraine_report.id
      assigns(:migraine_report).should eq(migraine_report)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MigraineReport" do
        expect {
          post :create, :migraine_report => valid_attributes
        }.to change(MigraineReport, :count).by(1)
      end

      it "assigns a newly created migraine_report as @migraine_report" do
        post :create, :migraine_report => valid_attributes
        assigns(:migraine_report).should be_a(MigraineReport)
        assigns(:migraine_report).should be_persisted
      end

      it "redirects to the created migraine_report" do
        post :create, :migraine_report => valid_attributes
        response.should redirect_to(MigraineReport.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved migraine_report as @migraine_report" do
        # Trigger the behavior that occurs when invalid params are submitted
        MigraineReport.any_instance.stub(:save).and_return(false)
        post :create, :migraine_report => {}
        assigns(:migraine_report).should be_a_new(MigraineReport)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MigraineReport.any_instance.stub(:save).and_return(false)
        post :create, :migraine_report => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested migraine_report" do
        migraine_report = MigraineReport.create! valid_attributes
        # Assuming there are no other migraine_reports in the database, this
        # specifies that the MigraineReport created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MigraineReport.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => migraine_report.id, :migraine_report => {'these' => 'params'}
      end

      it "assigns the requested migraine_report as @migraine_report" do
        migraine_report = MigraineReport.create! valid_attributes
        put :update, :id => migraine_report.id, :migraine_report => valid_attributes
        assigns(:migraine_report).should eq(migraine_report)
      end

      it "redirects to the migraine_report" do
        migraine_report = MigraineReport.create! valid_attributes
        put :update, :id => migraine_report.id, :migraine_report => valid_attributes
        response.should redirect_to(migraine_report)
      end
    end

    describe "with invalid params" do
      it "assigns the migraine_report as @migraine_report" do
        migraine_report = MigraineReport.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MigraineReport.any_instance.stub(:save).and_return(false)
        put :update, :id => migraine_report.id, :migraine_report => {}
        assigns(:migraine_report).should eq(migraine_report)
      end

      it "re-renders the 'edit' template" do
        migraine_report = MigraineReport.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MigraineReport.any_instance.stub(:save).and_return(false)
        put :update, :id => migraine_report.id, :migraine_report => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested migraine_report" do
      migraine_report = MigraineReport.create! valid_attributes
      expect {
        delete :destroy, :id => migraine_report.id
      }.to change(MigraineReport, :count).by(-1)
    end

    it "redirects to the migraine_reports list" do
      migraine_report = MigraineReport.create! valid_attributes
      delete :destroy, :id => migraine_report.id
      response.should redirect_to(migraine_reports_url)
    end
  end

end
