require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StressReportsController do

  # This should return the minimal set of attributes required to create a valid
  # StressReport. As you add validations to StressReport, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all stress_reports as @stress_reports" do
      stress_report = StressReport.create! valid_attributes
      get :index
      assigns(:stress_reports).should eq([stress_report])
    end
  end

  describe "GET show" do
    it "assigns the requested stress_report as @stress_report" do
      stress_report = StressReport.create! valid_attributes
      get :show, :id => stress_report.id
      assigns(:stress_report).should eq(stress_report)
    end
  end

  describe "GET new" do
    it "assigns a new stress_report as @stress_report" do
      get :new
      assigns(:stress_report).should be_a_new(StressReport)
    end
  end

  describe "GET edit" do
    it "assigns the requested stress_report as @stress_report" do
      stress_report = StressReport.create! valid_attributes
      get :edit, :id => stress_report.id
      assigns(:stress_report).should eq(stress_report)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new StressReport" do
        expect {
          post :create, :stress_report => valid_attributes
        }.to change(StressReport, :count).by(1)
      end

      it "assigns a newly created stress_report as @stress_report" do
        post :create, :stress_report => valid_attributes
        assigns(:stress_report).should be_a(StressReport)
        assigns(:stress_report).should be_persisted
      end

      it "redirects to the created stress_report" do
        post :create, :stress_report => valid_attributes
        response.should redirect_to(StressReport.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved stress_report as @stress_report" do
        # Trigger the behavior that occurs when invalid params are submitted
        StressReport.any_instance.stub(:save).and_return(false)
        post :create, :stress_report => {}
        assigns(:stress_report).should be_a_new(StressReport)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        StressReport.any_instance.stub(:save).and_return(false)
        post :create, :stress_report => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested stress_report" do
        stress_report = StressReport.create! valid_attributes
        # Assuming there are no other stress_reports in the database, this
        # specifies that the StressReport created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        StressReport.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => stress_report.id, :stress_report => {'these' => 'params'}
      end

      it "assigns the requested stress_report as @stress_report" do
        stress_report = StressReport.create! valid_attributes
        put :update, :id => stress_report.id, :stress_report => valid_attributes
        assigns(:stress_report).should eq(stress_report)
      end

      it "redirects to the stress_report" do
        stress_report = StressReport.create! valid_attributes
        put :update, :id => stress_report.id, :stress_report => valid_attributes
        response.should redirect_to(stress_report)
      end
    end

    describe "with invalid params" do
      it "assigns the stress_report as @stress_report" do
        stress_report = StressReport.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StressReport.any_instance.stub(:save).and_return(false)
        put :update, :id => stress_report.id, :stress_report => {}
        assigns(:stress_report).should eq(stress_report)
      end

      it "re-renders the 'edit' template" do
        stress_report = StressReport.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StressReport.any_instance.stub(:save).and_return(false)
        put :update, :id => stress_report.id, :stress_report => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested stress_report" do
      stress_report = StressReport.create! valid_attributes
      expect {
        delete :destroy, :id => stress_report.id
      }.to change(StressReport, :count).by(-1)
    end

    it "redirects to the stress_reports list" do
      stress_report = StressReport.create! valid_attributes
      delete :destroy, :id => stress_report.id
      response.should redirect_to(stress_reports_url)
    end
  end

end
